### ISSUE TITLE
(module "mmnText") does not exist

### ISSUE THREAD

**Issue by Benjamin-Scherf** [marcel-mathias-nolte/text-and-image-as-module#1]
Nach dem Update auf 
Contao 4.10.6
Inhaltselemente Bild und Text als Modul 1.0.15
erscheint folgender Fehler im Log. 

Module class "MarcelMathiasNolte\ContaoTextAndImageAsModuleBundle\Module\ModuleText" (module "mmnText") does not exist

Die Module werden im Frontend nicht mehr angezeigt und können im Backend nicht bearbeitet werden.
Mehrfaches Installieren des Packets bringt keine Änderung.

**Comment by Benjamin-Scherf** [comment]
Nachtrag: Eine weitere Änderung war das Isotope Update auf 2.7
Ebenfalls fällt wohl in den Zeitraum ein Update des Contao-Managers

**Comment by Benjamin-Scherf** [comment]
Ich habe jetzt alle möglichen Versuche vorgenommen. Contao Downgrade auf 4.9.12 und upgrade auf auf 4.11. Alle extensions deinstalliert wie Isotope und von der text-and-image-as-module die 13, 14, 15 ausprobiert. Dutzende male den Cache geleert. Das Problem besteht weiterhin. Ich habe ein Woche gut mit der Extension gearbeitet und rund 20 Module damit erstellt. Von einem Tag auf den anderen funktionierte es nicht mehr. Fehlermeldung beim öffnen eines BE Moduls ist der die Selbe, die in den Logs fürs FE auftaucht. 

Unter root/ vendor ist der Ordner marcel-mathias-nolte mit Module enthalten.
Unter system/modules ist kein Symlink zur Extension vorhanden. 

Aus dem Log 

[2021-02-17 14:15:02] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Class MarcelMathiasNolte\ContaoTextAndImageAsModuleBundle\Module\ModuleImage does not exist" at /home/www/test/vendor/contao/core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php line 94 {"exception":"[object] (ReflectionException(code: -1): Class MarcelMathiasNolte\\ContaoTextAndImageAsModuleBundle\\Module\\ModuleImage does not exist at /home/www/test/vendor/contao/core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php:94)"} []

Ich würde mich sehr sehr auf einen Vorschlag freuen. Vielen Dank


Ich habe den Test bei einen anderen System gemacht. In der 4.9.11 wird das Modul im Frontend ohne Fehlermeldung schon nicht mehr angezeigt. Ab 4.9.12 tritt die Fehlerwarnung auf.

**Comment by sdahlmann** [comment]
Ich habe auch den o.g. Fehler "Class MarcelMathiasNolte\ContaoTextAndImageAsModuleBundle\Module\ModuleText does not exist." Können Sie den Fehler bitte korrigieren? Ich bedanke mich schon im Voraus vielmals für die Behebung des Fehlers.

**Comment by marcel-mathias-nolte** [comment]
Wurde korrigiert. Problem war das das Autoload nun den psr-4 namespace so ernst nimmt, die ordnernamen müssen nun exakt dem namespace entpsprechen

**Comment by Benjamin-Scherf** [comment]
Vielen Dank
