### ISSUE TITLE
Contao 4.13 LTS

### ISSUE THREAD

**Issue by sdahlmann** [marcel-mathias-nolte/text-and-image-as-module#3]
Ich kann unter Contao 4.13 LTS RC3 bei Text (MCE) bei MCE-Text-Modul kein Bild hinzu fügen unter "Ein Bild hinzufügen". Dialog hängt sich auf beim Anhaken.
Wenn ich einen normalen Contao Artikel erstelle kann ich an selber stelle ein Bild hinzu fügen.
Nur ein Bild oder nur MCE-Text eingeben als Modul und abspeichern funktioniert einwandfrei.
Können Sie dieses eventl. bitte korrigieren. Ich benutze PHP 8.1.1.
Ich bedanke mich für das eventuelle Korrigieren des Fehlers schon im Voraus bei Ihnen.
![MCE-Text-Bild](https://user-images.githubusercontent.com/17680074/153971753-5fac956e-0c25-42a5-ad55-86f426cc1b2b.png)

**Comment by marcel-mathias-nolte** [comment]
fixed in 1.0.18
